from app.lookups_api.schemas import (
    CampusCreate,
    CampusResponse,
    CampusUpdate,
    CollegeCreate,
    CollegeResponse,
    CollegeUpdate,
    DepartmentCreate,
    DepartmentResponse,
    DepartmentUpdate,
    SchoolYearCreate,
    SchoolYearResponse,
    SchoolYearUpdate,
    SemesterCreate,
    SemesterResponse,
    SemesterUpdate,
)

__all__ = [
    "CampusCreate",
    "CampusUpdate",
    "CampusResponse",
    "CollegeCreate",
    "CollegeUpdate",
    "CollegeResponse",
    "DepartmentCreate",
    "DepartmentUpdate",
    "DepartmentResponse",
    "SchoolYearCreate",
    "SchoolYearUpdate",
    "SchoolYearResponse",
    "SemesterCreate",
    "SemesterUpdate",
    "SemesterResponse",
]
